- name: Install httpd
  yum:
    name: httpd
  notify: start httpd
- name: Add port 8080 to httpd config
  lineinfile:
    path: '/etc/httpd/conf/httpd.conf'
    regexp: '^Listen 80'
    line: Listen 8080
- name: delete useless .conf files
  file:
    path: '/etc/httpd/conf.d/{{ item }}'
    state: absent
  with_items:
    - autoindex.conf
    - userdir.conf
    - welcome.conf
- name: copy VirtualHost config
  template:
    src: 'virtualHost.conf.j2'
    dest: '/etc/httpd/conf.d/virtual.conf'
  notify: restart httpd
- name: copy jar file
  copy:
    src: '*.jar'
    dest: '/var/www/html/*.jar'