---
- name: Java installation
  become: yes
  yum:
    name: java-11-openjdk

- name: Create java_user on instance
  become: yes
  ansible.builtin.user:
    name: java_user
    group: admin
    password: admin

- name: Get jar file from folder
  become: yes
  get_url:
    url: https://github.com/Ozz007/sb3t/releases/download/1.0/sb3t-ws-1.0.jar
    dest: /home/java_user/

- name: Start java application
  shell: 'java -jar {{ JAR_PATH }}/{{ JAR_NAME }} -Xmx{{ JVM_SIZE }}'
  become_user : '{{ USER_NAME }}'
  async: 100